### DISCUSSION TITLE
General confusion of the docs

### DISCUSSION THREAD

**Discussion by botagas** [Schaka/janitorr#124] [Q&A] [answered]
Hello,

I've set up and got running a Janitorr instance. It has successfully connected to Jellyseerr, Jellyfin, Radarr, Sonarr, Jellystat. However, after a single run, I've noticed that there is something wrong. I see shows being added to Leaving Soon that are actively being watched (and that info is present in Jellystat). Is there a more definite wiki regarding Janitorr setup with Jellystat in particular?

This is my current config: 
```
server:
  port: 8978

logging:
  level:
    com.github.schaka: INFO
  threshold:
    file: NONE # Set to TRACE to enable file logging

file-system:
  access: true
  validate-seeding: true
  leaving-soon-dir: "/home/yunohost.multimedia/share/leavingsoon"
  media-server-leaving-soon-dir: "/home/yunohost.multimedia/share/leavingsoon"
  from-scratch: true
  free-space-check-dir: "/"

application:
  dry-run: true
  run-once: false
  whole-tv-show: true
  whole-show-seeding-check: false
  leaving-soon: 90d
  exclusion-tag: "janitorr_keep"

  media-deletion:
    enabled: true # Should this be disabled if used with Jellystat? No info.
    movie-expiration:
      5: 90d
      10: 90d
      15: 90d
      20: 120d
    season-expiration:
      5: 90d
      10: 90d
      15: 90d
      20: 120d

  tag-based-deletion:
    enabled: false
    minimum-free-disk-percent: 100
    schedules:
      - tag: 5 - demo
        expiration: 30d
      - tag: 10 - demo
        expiration: 7d

  episode-deletion: # This ignores Jellystat. Only grab history matters. It also doesn't clean up Jellyfin. There is NO seeding check either.
    enabled: false
    tag: janitorr_daily # Shows tagged with this will have all episodes of their LATEST season deleted by the below thresholds
    max-episodes: 10 # maximum (latest) episodes of this season to keep
    max-age: 30d # Maximum age to keep any episode at all - even the last 10 episodes would expire after 30 days in this example

clients:
  jellyfin:
    enabled: true
    url: "http://127.0.0.1:8095"
    api-key: "redacted"
    username: "redacted"
    password: "redacted"
    delete: true
    leaving-soon-tv: "Shows (Leaving Soon)"
    leaving-soon-movies: "Movies (Leaving Soon)"
  emby:
    enabled: false
    url: "http://localhost:8096"
    api-key: "redacted"
    username: Janitorr
    password: janitorr
    delete: true # Emby setup is required for JellyStat. However, if you don't want Janitorr to send delete requests to the Emby API, disable it here
    leaving-soon-tv: "Shows (Leaving Soon)"
    leaving-soon-movies: "Movies (Leaving Soon)"
  radarr:
    enabled: true
    url: "http://127.0.0.1:24744"
    api-key: "redacted"
    only-delete-files: false
  sonarr:
    enabled: true
    url: "http://127.0.0.1:52364"
    api-key: "redacted"
    delete-empty-shows: true
    determine-age-by: most_recent
  bazarr:
    enabled: false # Only used if you want to copy over subtitle files managed by Bazarr
    url: "http://localhost:6767"
    api-key: "redacted"

  jellyseerr:
    enabled: true
    url: "http://127.0.0.1:5055"
    api-key: "redacted"
    match-server: false
  jellystat:
    enabled: true
    url: "http://127.0.0.1:3000"
    api-key: "redacted"
```
