### DISCUSSION TITLE
Disabling the leaving soon logic

### DISCUSSION THREAD

**Discussion by tgudlek** [Schaka/janitorr#148] [Q&A] [answered]
Is there any way I can skip the whole leaving soon dance? It seems to be creating symlinks which my underlying file system doesn't really like -- so I'd rather just have it not handle leaving soon at all. If I remove the `leaving-soon-dir`, I get complaints that it's a required field. What should I do here?

```
server:
  port: 8978

logging:
  level:
    com.github.schaka: TRACE     # same as before
  threshold:
    file: NONE

file-system:
  access: true
  validate-seeding: false       # your setting
  leaving-soon-dir: "/<REDACTED>/data/library/leaving-soon"
  media-server-leaving-soon-dir: "/<REDACTED>/data/library/leaving-soon"
  from-scratch: true
  free-space-check-dir: "/"

application:
  dry-run: false
  run-once: false
  whole-tv-show: true
  whole-show-seeding-check: false
  # leaving-soon: 14d
  exclusion-tag: "janitorr_keep"

  media-deletion:
    enabled: true
    movie-expiration:
      100: 300d
    season-expiration:
      100: 400d

  tag-based-deletion:
    enabled: false
    minimum-free-disk-percent: 100
    schedules:
      - tag: 5 - demo
        expiration: 30d
      - tag: 10 - demo
        expiration: 7d

  episode-deletion:
    enabled: false
    tag: janitorr_daily
    max-episodes: 10
    max-age: 30d

clients:
  sonarr:
    enabled: true
    url: "http://localhost:8989/sonarr"
    api-key: "<REDACTED>"
    delete-empty-shows: true
    determine-age-by: oldest

  radarr:
    enabled: true
    url: "http://localhost:7878/radarr"
    api-key: "<REDACTED>"
    only-delete-files: false
    determine-age-by: oldest

  bazarr:
    enabled: false
    url: "http://localhost:6767"
    api-key: "<REDACTED>"

  jellyfin:
    enabled: true
    url: "http://localhost:8096"
    api-key: "<REDACTED>"
    username: Janitorr
    password: <REDACTED>
    delete: true

  jellyseerr:
    enabled: true
    url: "http://localhost:5055"
    api-key: "<REDACTED>=="
    match-server: false

  jellystat:
    enabled: true
    whole-tv-show: true 
    url: "http://localhost:3000"
    api-key: "<REDACTED>"
```
