### ISSUE TITLE
Symlinks not created

### ISSUE THREAD

**Issue by sjafferali** [Schaka/janitorr#10]
After setting this up and running it, the leaving soon collections are created in the filesystem and in jellyfin, however symlinks for the files that are leaving soon are not getting created, leading to both collections always being empty in jellyfin. Attempted running this with dry-run = False as well as dry-run = True. Filesystem access is also set to true in my configuration. 

Running docker image v0.9.3.

**Comment by sjafferali** [comment]
Hey @Schaka . I tried v0.9.3b, but symlinks are still not being created. 

If I increase the movie-expiration to something that matches some movies (running with dry-run = True), I do see that it logs deletion messages, so not sure why the symlink creation is not also occurring since the leaving-soon setting should also be matching some of my content. 

I am running it as root, and Jellyfin and Janitorr have the same volume mapping.

**Comment by Schaka** [comment]
I should probably adjust to docs to make it more clear how the options work.
If you set movie expiration to 120 days and leaving-soon to 14 days, it will add all the movies that are 106 to 119 days old to the leaving soon collections, until they approach 120 when they get deleted.

For debugging purposes, you can try setting it it to something simple like:
- movie-expiration: 15d
- leaving-soon: 14d

Keep in mind that leaving-soon won't touch any any files more recent than 15-14 days (i.e. only one day old). 

To add debug logging, you may add this at the top of your `application.yml`:
```
logging:
  level:
    com.github.schaka: TRACE
```

Currently, I only use debug messages, so DEBUG would be fine too.

**Comment by sjafferali** [comment]
Enabled trace logging and started running again with the below configuration:
```
logging:
  level:
    com.github.schaka: TRACE


server:
  port: 8978

# File system access (same mapping as Sonarr, Radarr and Jellyfin) is required to delete seasons by season and create "Leaving Soon" collections in Jellyfin
# Currently, Jellyfin does not support an easy way to add only a few seasons or movies to a collection, we need access to temporary hardlinks
# Additionally, checks to prevent deletion on currently still seeding media currently require file system access as well
file-system:
  access: true
  leaving-soon-dir: "/downloads/leaving-soon" # A directory this container can write to and Jellyfin can find under the same path - this will contain new folders with SymLinks to files for Jellyfin's "Leaving Soon" collections
  from-scratch: true # Clean up entire directory and rebuild from scratch - this can help with clearing orphaned data - turning this off can save resources (less writes to drive)

application:
  dry-run: true
  leaving-soon: 14d # 14 days before a movie is deleted, it gets added to a "Leaving Soon" type collection
  movie-expiration: 15d # 3 months - if a movie's files on your system are older than this, they will be deleted
  season-expiration: 15d # 2 months - if a season's files on your system are older than this, they will be deleted

clients:
  sonarr:
    url: "REDACTED"
    api-key: "REDACTED"
  radarr:
    url: "REDACTED"
    api-key: "REDACTED"
  jellyfin:
    enabled: true
    url: "REDACTED"
    api-key: "REDACTED"
    username: REDACTED
    password: REDACTED
  jellyseerr:
    enabled: true
    url: "REDACTED"
    api-key: "REDACTED"

# Currently not in use - intended to check seeding status and not delete currently seeding media
  torrent:
    type: QBITTORRENT
    name: qBittorrent
    auto-resume: true
    url: "locahost:8080"
    username: admin
    password: adminadmin
```

Log file that resulted: [janitorr_redacted.txt](https://github.com/Schaka/janitorr/files/14421967/janitorr_redacted.txt)
