### ISSUE TITLE
What does expiration do in tag-based-deletion?

### ISSUE THREAD

**Issue by Hugo-Persson** [Schaka/janitorr#106]
Hi!

I was wondering what the field `expiration` does in tag based deletion. For example here:
```yaml
  tag-based-deletion:
    enabled: true
    minimum-free-disk-percent: 100
    schedules:
      - tag: janitorr
        expiration: 7d
```

**Comment by Schaka** [comment]
You can choose to make every tag expire (delete) after a different duration.
This is in line with Janitorr's expiration-time for media-deletion. 

Since tags are handled separately and any tags you register are excluded from regular media deletion, you may use this to define your own schedule via tags. I personally don't use it but I know some users prefer it.

**Comment by Hugo-Persson** [comment]
Okay so in this case if I add the tag today it should be deleted in a week?

**Comment by Hugo-Persson** [comment]
What happens with media during this time? Can it be moved to leaving soon?

**Comment by Schaka** [comment]
You're defining the age at which point it will be deleted.

If your deletion period makes sense, symlinks will be created for leaving soon. Nothing is moved.

Obviously deleting after 7 days with 14 days set as leaving-soon won't work, because there is no period during which media is 14 days away from being deleted. It would just show up in leaving-soon right away or throw an exception, I'm not entirely sure which, as that's not an intended scenario.

**Comment by Hugo-Persson** [comment]
Okay so leaving soon takes into account all settings and if any media will be deleted in leaving soon time it will be moved there?

**Comment by Hugo-Persson** [comment]
So if I set leaving soon to 7d it will be added directly?

**Comment by Schaka** [comment]
There is a dry run mode, why don't you give it a try and see if it works as you wish.

**Comment by Hugo-Persson** [comment]
For me nothing is happening, I have the following config:
```yaml
  tag-based-deletion:
    enabled: true
    minimum-free-disk-percent: 100
    schedules:
      - tag: janitorr
        expiration: 15d

```
```yaml
application:
  dry-run: false
  run-once: false # If you enable this, Janitorr will clean up once and then shut down.
  whole-tv-show: true # activating this will treat as a whole show as recently download/watched from a single episode, rather than that episode's season - shows will be deleted as a whole
  whole-show-seeding-check: true # Turning this off, disables the seeding check entirely if whole-tv-show is enabled. Activating this check will keep a whole TV show if any season is still seeding (requires file access).
  leaving-soon: 14d # 14 days before a movie is deleted, it gets added to a "Leaving Soon" type collection (i.e. movies that are 76 to 89 days old)
  exclusion-tag: "janitorr_keep" # Set this tag to your movies or TV shows in the *arrs to exclude media from being cleaned up
```

The tag set like this in Sonarr
<img width="758" alt="image" src="https://github.com/user-attachments/assets/9679c860-99f6-4666-9b46-8d269544aa04" />


But logs say nothing about this show.
