### ISSUE TITLE
Not sure how determine-age-by works

### ISSUE THREAD

**Issue by ataaki** [Schaka/janitorr#126]
I've a tv-show that i added in sonarr in june 28th 2023. (630 days ago)
The first episode has beed downloaded in july 9th 2023. (619 days ago)
The last episode has been downloaded the november 4th 2024 (135 days ago)

I've set the following parameters in Janitorr:
```
application:
  dry-run: true
  run-once: false
  whole-tv-show: true
  whole-show-seeding-check: false
  leaving-soon: 14d
  exclusion-tag: "janitorr_keep"

  media-deletion:
    enabled: true
    movie-expiration:
      5: 240d
      10: 300d
    season-expiration:
      5: 240d
      10: 300d

  episode-deletion:
    enabled: false
    tag: janitorr_daily
    max-episodes: 10
    max-age: 30d

clients:
  sonarr:
    enabled: true
    url: ""
    api-key: ""
    delete-empty-shows: true
    determine-age-by: oldest
  radarr:
    enabled: true
    url: ""
    api-key: ""
    only-delete-files: false
    determine-age-by: oldest
```

The thing is that i've set `oldest` in `determine-age-by` and in the log it still imports the most recent date:

```
2025-03-19T21:52:57.069Z TRACE 1 --- [scheduling-1] c.g.s.j.s.sonarr.SonarrRestService       : Treat TV show as a whole - overwriting season import date - IMDB: tt1486217 imported at 2024-11-04T00:26:15
```

This results in the show not beeing picked up by the delete process.

I've tried to put `most_recent` in `determine-age-by` and i got the same imported date.
