### ISSUE TITLE
Feature Request: Implement Streamystats as Datasource

### ISSUE THREAD

**Issue by SirHardware** [Schaka/janitorr#130]
Due to the ongoing performance Issues of Jellyfin in Combination with Jellystats https://github.com/CyferShepard/Jellystat/issues/328, it would be a nice additon to implement support for https://github.com/fredrikburmester/streamystats?tab=readme-ov-file.

It is getting hard to justify a dead Jellyfin Server just for Media Deletion, since this is the only reason I have Jellystat still running.

**Comment by SirHardware** [comment]
Well I'm pretty sure it is the Streamystat Issue since stopping the Container helps solving the problem.
If it would be possible to implement it with the official Jellyfin Activity Plugin that would be even better, but I guessed there was a bigger reason you initially decided to go with Jellystat.

**Comment by Schaka** [comment]
If possible, please report back whether Streamystats 1.0 (released now) fixes the issue for you still. It seems to use the same API as Jellystat now, so I would expect it to cause the same issues Jellystat does, if they're inherent to Jellyfin.

If Streamystats does the trick, the [developer has agreed to expose an API](https://www.reddit.com/r/selfhosted/comments/1jqfzog/comment/ml72y4l/?context=3) that I could work around.

**Comment by SirHardware** [comment]
I have the latest Version now running for 3 days and so far it didn't crash my Jellyfin

**Comment by Schaka** [comment]
Take a look at https://github.com/Schaka/janitorr/pull/138 and the resulting images `138-merge` and `native-amd64-138-merge` (and later `native-138-merge`).

I've done some limited testing for access, but it's quite possible it might behave differently on different systems and with other libraries.

**Comment by JamsRepos** [comment]
> Take a look at [#138](https://github.com/Schaka/janitorr/pull/138) and the resulting images `138-merge` and `native-amd64-138-merge` (and later `native-138-merge`).
> 
> I've done some limited testing for access, but it's quite possible it might behave differently on different systems and with other libraries.

I'm now running `native-138-merge` and have disabled my Jellystat in favour for Streamystats, so i'll let you know how my testing goes.

**Comment by Schaka** [comment]
`Header missing streamystats-token`

Do you potentially use a reverse proxy that might remove part of the cookie header?

For documentation's sake, to get a valid bearer token in Streamystats, you have to perform a user login.

The user login is a post request
```
Headers:
Content-Type: text/plain;charset=UTF-8
Next-Action: f8be693f8ad21105acbf6b03f935735a81ceacbd # Does not work without this header

Body:
[{
    "username": "${properties.username}",
    "password": "${properties.password}",
    "serverId": 1
}]

POST streamystats:3000/servers/1/login
```

The response has no content, but has 2 `Set-Cookie` headers, one containing `streamystats-token` and one containing URL encoded `streamystats-user`.

The token needs to be extract from that header and used for API requests.

If you have the means, please execute this and see what results you get. You need Streamystats 1.3.0 at the minimum.

**Comment by s1mpleman** [comment]
Might have died before I was trying it in Janitorr that's working now I've reset up Streamystats sorry about that.

**Comment by SirHardware** [comment]
I tried to run ``native-138-merge`` by simply adding the Streamystats Section in my existing config file and starting up the new Image.
It doesn't start with following error:
```
Failed to bind properties under 'file-system' to com.github.schaka.janitorr.config.FileSystemProperties:

    Reason: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.schaka.janitorr.config.FileSystemProperties.<init>, parameter leavingSoonDir
```
Anything else I have to adjust in the Config?

**Comment by Schaka** [comment]
I would assume your config isn't being loaded correctly. Were you not using the native image before?
If you weren't, I'd suggest making the switch according to the docs. Or stick with `138-merge` for now.

**Comment by SirHardware** [comment]
I switched from ``native-stable``. So it shouldn't be a problem.

**Comment by SirHardware** [comment]
Maybe I understood something wrong 
So I am trying with following block:
```yaml
application:
  dry-run: true
  run-once: false # If you enable this, Janitorr will clean up once and then shut down.
  whole-tv-show: false # activating this will treat as a whole show as recently download/watched from a single episode, rather than that episode's season - shows will be deleted as a whole
  whole-show-seeding-check: false # Turning this off, disables the seeding check entirely if whole-tv-show is enabled. Activating this check will keep a whole TV show if any season is still seeding (requires file access).
  # leaving-soon: 14d # 14 days before a movie is deleted, it gets added to a "Leaving Soon" type collection (i.e. movies that are 76 to 89 days old)
  exclusion-tag: "janitorr_keep" # Set this tag to your movies or TV shows in the *arrs to exclude media from being cleaned up
  leaving-soon-type: NONE
  leaving-soon-dir: "/data/media/fucking/hell"
```
and it still throws the error.

**Comment by Schaka** [comment]
With the `leaving-soon-dir` available, the error is likely different. `leaving-soon-type` doesn't go there, it goes under the Jellyfin/Emby keys, like:

```
jellyfin:
    enabled: true
    url: "http://localhost:8096"
    api-key: "4da8d93992804489ba2d1f0e31b8316c"
    username: Janitorr
    password: janitorr
    delete: true
    leaving-soon-tv: "Shows (Leaving Soon)"
    leaving-soon-movies: "Movies (Leaving Soon)"
    leaving-soon-type: MOVIES_AND_TV
```

I generally try to keep everything backwards compatible, but this change was required.
