### ISSUE TITLE
Symlinks not working

### ISSUE THREAD

**Issue by retardgerman** [Schaka/janitorr#149]
I have a problem with the symlinks for janitorr and jellyfin. Logs:

```
2025-06-05T09:37:58.076Z  INFO 1 --- [   scheduling-1] c.g.s.j.m.AbstractMediaServerService     : Can't find original movie folder - no links to create /data/media/movies/Flight Risk (2025) [imdbid-tt10078772]/Flight Risk (2025) [imdbid-tt10078772] - [German DL][Bluray-2160p][DV HDR10Plus][EAC3 5.1][x265]-VECTOR.mkv

```

Both containers have the same owner, so it should not be a permission problem. 

```

  janitorr:
    container_name: janitorr
    image: ghcr.io/schaka/janitorr:native-stable
    user: ${PUID}:${PGID}
    volumes:
      - ${DOCKERCONFDIR}/janitorr/config/application.yml:/workspace/application.yml
      - ${DOCKERCONFDIR}/janitorr/logs:/logs
      - ${DOCKERSTORAGEDIR}/media:/data
    environment:
      - THC_PATH=/health
      - THC_PORT=8081
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      start_period: 30s
      interval: 5s
      retries: 3

  
  jellyfin:
    container_name: jellyfin
    image: hotio/jellyfin
    privileged: true # Für Hardware-Transcoding
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 8096:8096
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/jellyfin:/config:rw
      - ${DOCKERSTORAGEDIR}/media:/data/media:rw
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 
      - /dev/dri/card0:/dev/dri/card0
    tmpfs:
      - /transcode

```

my janitorr config:

```yml

server:
  port: 8978

logging:
  level:
    com.github.schaka: INFO
  threshold:
    file: NONE

file-system:
  access: true
  validate-seeding: false
  leaving-soon-dir: '/data/media/leaving-soon'
  media-server-leaving-soon-dir: '/data/media/leaving-soon'
  from-scratch: true
  free-space-check-dir: '/'

application:
  dry-run: false
  run-once: false
  whole-tv-show: false
  whole-show-seeding-check: false
  leaving-soon: 14d
  exclusion-tag: 'janitorr_keep'

media-deletion:
  enabled: true
  movie-expiration:
    5: 15d
    10: 30d
    15: 60d
    20: 90d
  season-expiration:
    5: 15d
    10: 20d
    15: 60d
    20: 120d

tag-based-deletion:
  enabled: true
  minimum-free-disk-percent: 100
  schedules:
    - tag: janitorr-30
      expiration: 30d
    - tag: janitorr-7
      expiration: 7d

episode-deletion:
  enabled: false
  tag: janitorr_daily
  max-episodes: 10
  max-age: 30d

clients:
  sonarr:
    enabled: true
    url: 'http://192.168.1.59:32782'
    api-key: '******'
    delete-empty-shows: true
    determine-age-by: MOST_RECENT

  radarr:
    enabled: true
    url: 'http://192.168.1.59:32783'
    api-key: '******'
    only-delete-files: false
    determine-age-by: most_recent

  bazarr:
    enabled: true
    url: 'http://192.168.1.59:6767'
    api-key: '******'

  jellyfin:
    enabled: true
    url: 'http://192.168.1.59:8096'
    api-key: '******'
    username: Janitorr
    password: '******'
    delete: true
    leaving-soon-tv: 'Serien (Leaving Soon)'
    leaving-soon-movies: 'Filme (Leaving Soon)'
    leaving-soon-type: MOVIES_AND_TV

  jellyseerr:
    enabled: true
    url: 'http://192.168.1.59:5055'
    api-key: '******'
    match-server: false

  jellystat:
    enabled: false
    whole-tv-show: false
    url: 'http://jellystat:3000'
    api-key: '******'

  streamystats:
    enabled: true
    whole-tv-show: false
    url: 'http://192.168.1.59:3001'
    username: Jan
    password: '******'

```
