### ISSUE TITLE
Feature Enhancement Request: Custom Deletion Schedules Based on Tags

### ISSUE THREAD

**Issue by coltondick** [Schaka/janitorr#18]
## Feature Enhancement Request: Custom Deletion Schedules Based on Tags

**Summary:**  
The recent implementation of using tags to exclude media from the deletion schedule in Sonarr/Radarr has been a significant advancement. I am proposing an enhancement where we can create custom deletion schedules based on specific tags.

**Details:**  
Jellyseer offers a feature to automatically tag media with a user ID and Display name of the requester. This functionality could be extended in Janitorr to manage media lifecycles more effectively.

**Suggested Feature:**  
- **Custom Deletion Schedules Based on Tags:** The ability to set custom deletion schedules for media based on their tags. 
- **Example Use Case:** For instance, any media tagged with `5 - demo` should be automatically scheduled for deletion after 30 days.

You could have a section in the `application.yml` similar to the following:

```yml
  # Custom Tag-Based Deletion Schedules
  tagBasedDeletion:
    enabled: true
    schedules:
      - tag: "5 - demo"
        expiration: 30d # Delete media with this tag after 30 days
```
This feature would significantly improve media management by allowing for more nuanced and user-specific handling of media lifecycles.
