### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by mysteriousHerb** [Schaka/janitorr#88]
When i start the page at ip:8978, this is what i got:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Nov 03 20:21:31 UTC 2024
There was an unexpected error (type=Not Found, status=404).

My docker compose:
```
  janitorr:
    # cleaning the media files after watching etc.
    container_name: janitorr
    image: ghcr.io/schaka/janitorr:stable
    user: 1000:1000 # Replace with your user who should own your application.yml file
    ports:
      - 8978:8978
    volumes:
      - ./janitorr/config/application.yml:/workspace/application.yml
      - ./janitorr/logs:/logs
      - ${DATA_ROOT}:/data
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8978/health | grep UP || exit 1"
      start_period: 30s
      interval: 5s
      retries: 3
    restart: unless-stopped
```

Config is using th;e default template, but i disabled jellyseer and jellystat, do i need them>??
